---
title: "Covid91 vaccine study Final2023"
author: "Estrella Aguilar "
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---



```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
OldData <-read.csv(file="final.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- OldData %>% mutate(infected = recode(infected, covid19 = "covid", OK = "OK" )) %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
FinalData$treatment <- relevel(FinalData$treatment,ref="placebo")
#FinalData$infected <- relevel(FinalData$infected,ref="OK")
Males = filter(FinalData, sex =="M")
Females = filter(FinalData, sex =="F")
LGBTQ = filter(FinalData, LGBTQ =="gay")
Druggies = filter(FinalData, DrugUser =="yes")
```





# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

# Code block modification 

I made some changes to the block of code on line 14, I used Tay's example as an example for what changes to make. I separated each variable into its own line and changed its name to Males, Females, LGBTQ and DrugUser(because druggies was not found). I also changed some formatting to seperate the people who got covid and the people who did not get covid. This allowed for all 4 groups to pop up in the environment panel. 

## Males






### Inferential 





## Females


## LGBTQ



## Druggies


# Overall Results and Conclusions